package com.sifast.appsocle.tasks;


import android.app.Activity;
import android.app.ProgressDialog;
import android.os.AsyncTask;
import android.widget.Toast;

import com.firebase.client.Firebase;
import com.sifast.appsocle.R;
import com.sifast.appsocle.models.User;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Created by Asus on 14/06/2016.
 */
public class RegistrationTask extends AsyncTask {
    private User registeredUser;
    private Activity loginActivity;
    private ProgressDialog progress;
    private String dbUrl;
    public RegistrationTask(User registeredUser, Activity loginActicity) {
        this.registeredUser = registeredUser;
        this.loginActivity= loginActicity;
    }

    @Override
    protected Object doInBackground(Object[] params) {
        this.dbUrl = loginActivity.getResources().getString(R.string.dbUrl);
        //dialog to say to the user that he must wait
        loginActivity.runOnUiThread(new Runnable() {
            @Override
            public void run() {
                progress = ProgressDialog.show(loginActivity, loginActivity.getBaseContext().getString(R.string.registrationLabel),
                        loginActivity.getBaseContext().getString(R.string.waitMsg), true);
            }
        });
        //add the user
        register();
        loginActivity.runOnUiThread(new Runnable() {
            @Override
            public void run() {
                progress.dismiss();
            }
        });
        return null;
    }

    public void register() {
        Firebase ref = new Firebase(dbUrl);
        // Generate a reference to a new location and add some data using push()
        Firebase postRef = ref.child("users");
        Firebase newPostRef = postRef.push();
        // Add some data to the new location
        Map<String, String> post = new HashMap<String, String>();
        post.put("username", registeredUser.getUsername());
        post.put("password", String.valueOf(registeredUser.getPassword().toString().hashCode()));
        post.put("dateOfBirth", registeredUser.getDateOfBirth());
        post.put("signUpDate", registeredUser.getSignUpDate());
        post.put("email", registeredUser.getEmail());
        newPostRef.setValue(post);
        // Get the unique ID generated by push()
        String postId = newPostRef.getKey();
        String sendTO = registeredUser.getEmail();
        List<String> toEmailList = Arrays.asList(sendTO
                .split("\\s*,\\s*"));
        //set the email's data
        String emailTex = loginActivity.getResources().getString(R.string.emailWelcomeText);
        String email = loginActivity.getResources().getString(R.string.email);
        String passwordMail = loginActivity.getResources().getString(R.string.passwordMail);
        String subject = loginActivity.getResources().getString(R.string.welcomeSubject);
        new MailSendingTask().execute(email, passwordMail, toEmailList, subject, emailTex);
    }

    public User getRegisteredUser() {
        return registeredUser;
    }

    public void setRegisteredUser(User registeredUser) {
        this.registeredUser = registeredUser;
    }

    public Activity getLoginActicity() {
        return loginActivity;
    }

    public void setLoginActicity(Activity loginActicity) {
        this.loginActivity = loginActicity;
    }

    public ProgressDialog getProgress() {
        return progress;
    }

    public void setProgress(ProgressDialog progress) {
        this.progress = progress;
    }

    public String getDbUrl() {
        return dbUrl;
    }

    public void setDbUrl(String dbUrl) {
        this.dbUrl = dbUrl;
    }
}
